apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-{{ .Values.color }}-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "false"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
    - http:
        paths:
          - path: /{{ .Values.color }}
            backend:
              serviceName: my-{{ .Values.color }}-service
              servicePort: 80
